<div class="fieldset-wrapper order-information">
    <?php
        /** @var \StoreKeeper\StoreKeeper\Block\Adminhtml\Order\View\Tab\StoreKeeper $block */
        $order = $block->getOrder();
        $orderDetached = $block->getOrderDetached();
    ?>

    <p>
        <strong><?=__("Last synchronised at") ?></strong><br/>
        <?php if ($storekeeperOrderLastSync = $order->getStorekeeperOrderLastSync()) : ?>
            <?= date("Y-m-d H:i:s", $storekeeperOrderLastSync) ?>
        <?php else : ?>
            <?= __("Never") ?>
        <?php endif ?>
    </p>

    <p>
        <strong><?= __("Pending synchronisation") ?></strong><br/>
        <?= $order->getStorekeeperOrderPendingSync() ? __("Yes") : __("No") ?>
    </p>

    <?php if ($storekeeperId = $order->getStorekeeperId()) : ?>
        <p>
            <strong><?=__("Order ID") ?></strong><br/>
            <?= $storekeeperId ?>
            <a href="<?= $block->getStorekeeperBackofficeOrderUrl($order) ?>" target="_blank">
                <?= __("View in backoffice") ?>
            </a>
        </p>
    <?php endif ?>

    <?php if ($storekeeperOrderNumber = $order->getStorekeeperOrderNumber()) : ?>
        <p>
            <strong><?=__("Order #") ?></strong><br/>
            <?= $storekeeperOrderNumber ?>
        </p>
    <?php endif ?>

    <?php
    /** @var \StoreKeeper\StoreKeeper\Block\Adminhtml\Order\View\Tab\StoreKeeper $block */
    $orderDetached = $block->getOrderDetached();
    ?>

    <div>
        <label for="order_detached"><?php echo __('Order Detached'); ?></label>
        <select id="order_detached" name="order_detached">
            <option value="1" <?php echo $orderDetached ? 'selected' : ''; ?>><?php echo __('Yes'); ?></option>
            <option value="0" <?php echo !$orderDetached ? 'selected' : ''; ?>><?php echo __('No'); ?></option>
        </select>
        <button type="button" id="save_order_detached"><?php echo __('Save'); ?></button>
    </div>

    <script>
        require(['jquery'], function($) {
            $('#save_order_detached').on('click', function() {
                $.ajax({
                    url: '<?php echo $block->getSaveUrl(); ?>',
                    type: 'POST',
                    data: {
                        order_detached: $('#order_detached').val(),
                        form_key: window.FORM_KEY
                    },
                    success: function(response) {
                        alert('<?php echo __('Saved successfully'); ?>');
                    },
                    error: function(response) {
                        alert('<?php echo __('Error saving the field'); ?>');
                    }
                });
            });
        });
    </script>

</div>
