<fieldset class="admin__fieldset" id="export_filter_container" style="margin-left: 100px">
    <div>
        <span style="margin-right: 30px; font-size: 1.6rem; font-weight: 600;"><?= $block->escapeHtml(__('Export Products')) ?></span>
        <button class="action-scalable" type="button" onclick="window.location.href = '<?= $block->escapeHtml($block->getGenerateUrl()) ?>'">
            <span><?= $block->escapeHtml(__('Generate')) ?></span>
        </button>
    </div>
</fieldset>
